### PR TITLE
Expose the 'specPath' when looking up

### PR DESCRIPTION
**Pull request by Pchelolo**
I'm prototyping a change-prop  based solution to collect statistics on Varnish level for requests to RESTBase and need this to happen first.

Bug: T122245

### CODE REVIEW

**Comment by gwicke** [comment]
Could you provide some background on why we the [`specInfo.path` property we use for hyperswitch metrics](https://github.com/wikimedia/hyperswitch/blob/5fa6f87027e11883addde29eafcbd5443f82adfe/lib/filters/metrics.js#L9) is not good enough here?

**Comment by Pchelolo** [comment]
@gwicke The idea is that for regular metrics we use router from `hyperswitch` that loads a whole bunch of other stuff too and making it support a `dry run` so that it doesn't try to load resources, filters etc is harder, then just using a plain `swagger-router`. The resulting 'path' would be exactly the same as if we've used the hyperswitch's router.

**Comment by gwicke** [comment]
@Pchelolo, what happens if we load a (possibly tweaked) version of the merged, public spec into hyperswitch? Shouldn't that already remove all resources etc?

**Comment by Pchelolo** [comment]
Not really, there's some leftover stuff, also operationId doesn't exist, some filters are leftover in the merged spec, it's trying to load resources. I guess we could make an effort to clean up the public spec though..

**Pull request closed without merging**
