### PR TITLE
URI.params support

### PR DESCRIPTION
**Pull request by d00rman**
This PR adds support for the URI.params property, and a couple of tests for it.

### CODE REVIEW

**Comment by gwicke** [comment]
How is this going to be used?

**Comment by d00rman** [comment]
> How is this going to be used?

Like [this](https://github.com/wikimedia/restbase/blob/modules/lib/restbase.js#L56). But, in fact, now that I think about it, it would probably be better to rewrite that line in restbase.js not to query `req.uri.params` but `req.params` ... What do you think?

**Comment by gwicke** [comment]
@d00rman, I'm pretty sure `req.uri.params` won't be defined at that point, as the URL will likely be an actual value and not a pattern. Hmmm.. thinking about it, we actually _must not_ treat a URL supplied by the client as a pattern. Right now we do in the `URI` constructor. Maybe we should have an optional flag to request parsing as a pattern, with the default being no pattern parsing?

Additionally, `req.params` won't be available either, as that is only built up while traversing the router. `URI.path[1]` is probably as good as we can get.

**Comment by earldouglas** [comment]
This reminds me of the trouble we had with missing vs. single- vs. double-serialization of Cassandra values.  It occurs becuase we are overloading the implied type of `req`, leaving us unable to distinguish its type at any given point.

Would it be more stable to use explicitly different data types for this kind of situation?

e.g. a `req` is a data structure that comes in from the Web layer and has a stringy uri property, while a `restbaseReq` is a data structure that has had its URI parsed and params extracted, its body parsed and converted (as necessary) from form-urlencoded to JSON, etc.?

**Comment by gwicke** [comment]
@d00rman, closing as we have solved this differently since.

**Pull request closed without merging**
