### PR TITLE
Moved templates to router and general refactoring

### PR DESCRIPTION
**Pull request by Pchelolo**
Move `reqTemplate` library from RESTBase to swagger-router to allow reuse.

### CODE REVIEW

**Comment by d00rman** [comment]
Heh, yet another huge PR. These are becoming your specialty @Pchelolo :)

**Comment by Pchelolo** [comment]
@d00rman Actually, there's nothing happening here, mostly copy-paste, bumping dependency versions, and adding jscs.

**Comment by d00rman** [comment]
Let's add `sudo: false` to `.travis.yml` so that tests run in containers.

**Comment by Pchelolo** [comment]
@d00rman updated, now travis runs in containers

**Comment by d00rman** [comment]
Published as v0.2.0

**Pull request merged**
